// USER REDUCER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';

// UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const SET_DRAWER = 'SET_DRAWER';
export const MOBILE = 'MOBILE';

// COMMUNITY REDUCER
export const COMMUNITY_ACTIONS = {
    SHOW: "SHOW",
};

// ALERT REDUCER TYPES
export const ALERT_TYPES = {
    SUCCESS: "SUCCESS",
    CLEAR: "CLEAR",
    ERROR: "ERROR",
};